PRAGMA foreign_keys=OFF;
BEGIN TRANSACTION;
CREATE TABLE IF NOT EXISTS "Wikipedia" (
    "date" TEXT NOT NULL PRIMARY KEY,
    "count" INTEGER NOT NULL
);
INSERT INTO Wikipedia VALUES('2024-02-17',6785088);
COMMIT;
